render_target_path_vulkan = "fbo"
vulkan_device = -1
execute_unclipped_draw_vs_on_cpu = true
execute_unclipped_draw_vs_on_cpu_with_scissor = false
depth_float24_convert_in_pixel_shader = true
guest_vblank_unlocked = false
readback_resolve = "full"
readback_memexport = true
readback_memexport_fast = true
clear_memory_page_state = false
occlusion_query_enable = true
async_shader_compilation = false
video_mode_width = 1280
video_mode_height = 720
video_mode_refresh_rate = 60
fullscreen = true
vsync = false
native_2x_msaa = false
swap_post_effect = "none"
bind_debug_overlay = "Home"
vulkan_log_sync_timing = false
vulkan_log_render_targets = false
vulkan_log_resolve_contents = false
