<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>1.1.0</Version>
    <AssemblyName>FifaStreetSetup</AssemblyName>
    <ApplicationIcon>..\recomp-template\src\fifastreet.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="cover.jpg" LogicalName="cover.jpg" />
    <EmbeddedResource Include="credit-patch.json.gz" LogicalName="credit-patch.json.gz" />
    <EmbeddedResource Include="..\recomp-template\src\fifastreet.ico" LogicalName="fifastreet.ico" />
    <EmbeddedResource Include="bundle.zip" LogicalName="bundle.zip" Condition="'$(BundlePath)' == '' and Exists('bundle.zip')" />
    <EmbeddedResource Include="$(BundlePath)" LogicalName="bundle.zip" Condition="'$(BundlePath)' != ''" />
    <EmbeddedResource Include="$(PrecompiledManifest)" LogicalName="precompiled-mode" Condition="'$(PrecompiledManifest)' != ''" />
  </ItemGroup>

</Project>
