<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>fifastreet.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="cover.jpg" LogicalName="cover.jpg" />
    <EmbeddedResource Include="fifastreet.ico" LogicalName="fifastreet.ico" />
  </ItemGroup>

</Project>
